### ISSUE TITLE
Settings page has no action bar back

### ISSUE THREAD

**Issue by ischeinkman** [ischeinkman/OfficialRamonApp#13]

**Comment by ischeinkman** [comment]
An option would be rewriting the settings page as a PreferenceFragment inside a standard activity and then pass the calling activity name inside the intent to allow back navigation from any screen.

**Comment by ghost** [comment]
Fixed.

**Comment by ischeinkman** [comment]
Don't close an issue until the PR has been cleared.

**Comment by ghost** [comment]
OK, sorry.
