### ISSUE TITLE
Cannot delete Alephs from contact list.

### ISSUE THREAD

**Issue by ghost** [ischeinkman/OfficialRamonApp#24]
I WANT TO DELETE YOU! FROM EXISTENCE! MUHAHAHAHA

**Comment by ischeinkman** [comment]
Is this functionality really necessary? Do we want alephs to have complete control of the contact list?

**Comment by ghost** [comment]
You got a point. Should I close the issue?

**Comment by ischeinkman** [comment]
Closed.
